#!python
import os

# build with `scons --debug_build` for debug.
AddOption(
    '--debug_build',
    action='store_true',
    help='debug build',
    default=False)

env = Environment(ENV = os.environ, tools = ['mingw'])
path = ['C:\\MinGW_63\\bin']
env.PrependENVPath('PATH', path)
env.Append(CXXFLAGS='--std=c++17') 

 
if GetOption('debug_build'):
    env.ParseFlags('-DDEBUG')
    variant_dir = 'build/BlackJack_debug'
else:
    variant_dir = 'build/BlackJack_release'
 
SConscript('src/SConscript', variant_dir=variant_dir, duplicate=False, exports=['env'])